version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo "Zipping Lambda function code..."
      - zip -r deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "Updating Lambda function code..."
      - aws lambda update-function-code --function-name github-to-lambda-demo --zip-file fileb://deployment_package.zip
      - echo "DONE!!"
